
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ChakraProvider} from '@chakra-ui/react'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Exercice CV',
  description: 'Generated by Gaelle',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">

      <body>
      <ChakraProvider>
        {children}
      
      </ChakraProvider>
      </body>

    </html>
  )
}
